# Generated by Django 5.0 on 2024-02-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='size',
            field=models.CharField(choices=[('SC', 'small cap'), ('MC', 'mid cap'), ('LC', 'large cap')], default='Si', max_length=2),
            preserve_default=False,
        ),
    ]
