# Generated by Django 5.0 on 2024-02-26 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company Details'},
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name', 'symbol'], name='company_name_3f6494_idx'),
        ),
    ]
