# Generated by Django 5.0 on 2024-02-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_company_options_alter_company_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='indus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
    ]
