# Generated by Django 5.0 on 2024-07-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_catogory_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='broker_ptr',
        ),
        migrations.RemoveField(
            model_name='events',
            name='catogory',
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='company',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='company',
        ),
        migrations.DeleteModel(
            name='indus',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='share',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
        migrations.DeleteModel(
            name='premiumuser',
        ),
        migrations.DeleteModel(
            name='broker',
        ),
        migrations.DeleteModel(
            name='founder',
        ),
        migrations.DeleteModel(
            name='Catogory',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioItem',
        ),
    ]
